name: flutter_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.1.6
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/jzoom/flutter_swiper

dependencies:
  flutter:
    sdk: flutter

  transformer_page_view:
    git: https://github.com/Ashutosh101010/transformer_page_view.git
  flutter_page_indicator:
    git: https://github.com/Ashutosh101010/flutter_page_indicator.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
